services:
  - type: web
    name: ragul-products-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ragul-products-db
          property: connectionString
      - key: ALLOWED_ORIGINS
        value: "*"

databases:
  - name: ragul-products-db
